# Generated by Django 4.0.3 on 2022-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oriente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stratum', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('mtsC', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='rest_antioquia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stratum', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('mtsC', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='valle_aburra',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stratum', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('mtsC', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('barrio', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
